name: Generate Google Shopping Feed

on:
  schedule:
    # Exécution chaque nuit à 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Permet le lancement manuel

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Feed Generation Script
        env:
          WOO_URL: ${{ secrets.WOO_URL }}
          WOO_CK: ${{ secrets.WOO_CK }}
          WOO_CS: ${{ secrets.WOO_CS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        run: python main.py
